### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by mr-c** [RDFLib/html5rdf#1]
Thank you!

**Comment by bollwyvl** [comment]
It might also be reasonable to include the test suite in PyPI `sdist`s.

**Comment by mr-c** [comment]
> It might also be reasonable to include the test suite in PyPI `sdist`s.

Yep, I sent a PR for that: https://github.com/RDFLib/html5rdf/pull/2

**Comment by ashleysommer** [comment]
Will do.

**Comment by ashleysommer** [comment]
@bollwyvl  @mr-c 

v1.2.1 is release now with the testdata git submodule included in the sdist, and the release tagged.

**Comment by mr-c** [comment]
> @bollwyvl @mr-c
> 
> v1.2.1 is release now with the testdata git submodule included in the sdist, and the release tagged.

Thank you @bollwyvl !
